/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('antdv-next')['Affix']
    AApp: typeof import('antdv-next')['App']
    AAvatar: typeof import('antdv-next')['Avatar']
    ABadge: typeof import('antdv-next')['Badge']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACardMeta: typeof import('antdv-next')['CardMeta']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACol: typeof import('antdv-next')['Col']
    AColorPicker: typeof import('antdv-next')['ColorPicker']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADatePicker: typeof import('antdv-next')['DatePicker']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADivider: typeof import('antdv-next')['Divider']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AFlex: typeof import('antdv-next')['Flex']
    AFloatBackTop: typeof import('antdv-next')['BackTop']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutFooter: typeof import('antdv-next')['LayoutFooter']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AListy: typeof import('antdv-next')['Listy']
    AMenu: typeof import('antdv-next')['Menu']
    AModal: typeof import('antdv-next')['Modal']
    APopconfirm: typeof import('antdv-next')['Popconfirm']
    APopover: typeof import('antdv-next')['Popover']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARow: typeof import('antdv-next')['Row']
    ASegmented: typeof import('antdv-next')['Segmented']
    ASelect: typeof import('antdv-next')['Select']
    ASpin: typeof import('antdv-next')['Spin']
    ASwitch: typeof import('antdv-next')['Switch']
    ATabPane: typeof import('antdv-next')['TabPane']
    ATabs: typeof import('antdv-next')['Tabs']
    ATag: typeof import('antdv-next')['Tag']
    ATextarea: typeof import('antdv-next')['TextArea']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATree: typeof import('antdv-next')['Tree']
    ATreeSelect: typeof import('antdv-next')['TreeSelect']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
    AUpload: typeof import('antdv-next')['Upload']
    Bar: typeof import('./../src/components/Scrollbar/Bar.vue')['default']
    Page: typeof import('./../src/components/page/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./../src/components/Scrollbar/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TodoGroup: typeof import('./../src/components/todo/TodoGroup.vue')['default']
    TodoGroupModal: typeof import('./../src/components/todo/actions/TodoGroupModal.vue')['default']
    TodoList: typeof import('./../src/components/todo/TodoList.vue')['default']
    TodoModal: typeof import('./../src/components/todo/actions/TodoModal.vue')['default']
  }
}
